[project]
name = "qwenagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "qwen-agent[code-interpreter,gui,mcp,rag]>=0.0.26",
    "yfinance>=0.2.62",
]
